 
 
 export const data = [
    {   id:0,
        nom:'ibiza',
        marque:'seat',
        couleur:'gris-mauve',
        puissance:'102',
        pictures:'',
        energie:'E',
        visible:true,    },
    {id:1,
        nom:'leon',
        marque:'seat',
        couleur:'orange',
        puissance:'143',
        pictures:'',
        energie:'D',
        visible:true,

    },
    {id:2,
        nom:'ibiza',
        marque:'seat',
        couleur:'gris-mauve',
        puissance:'102',
        pictures:'',
        energie:'E',
        visible:true,
    },
    {id:3,
        nom:'leon',
        marque:'seat',
        couleur:'orange',
        puissance:'143',
        pictures:'',
        energie:'D',
        visible:false,
    },
]
